

DROP TABLE IF EXISTS challenges;
CREATE TABLE challenges (
    id SERIAL,
    question_text text NOT NULL,
    expected_query text NOT NULL,
    difficulty varchar(50) NOT NULL DEFAULT 'easy',
    category varchar(100) NOT NULL,
    level varchar(50) NOT NULL DEFAULT 'Beginner',
    hint text,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

INSERT INTO challenges (question_text, expected_query, difficulty, category, level, hint) VALUES
('Show the first 5 rows from the countries table.', 'SELECT * FROM countries LIMIT 5', 'easy', 'Table Exploration', 'Beginner', ' * and LIMIT 5.'),
('List the names of the first 10 countries.', 'SELECT name FROM countries LIMIT 10', 'easy', 'Table Exploration', 'Beginner', 'Select only the name column.'),
('Show country names and capitals for the first 10 countries.', 'SELECT name, capital FROM countries LIMIT 10', 'easy', 'Table Exploration', 'Beginner', 'Select name and capital from countries.'),
('Show the first 8 rows from the states table.', 'SELECT * FROM states LIMIT 8', 'easy', 'Table Exploration', 'Beginner', ' states table with LIMIT.'),
('List the first 12 state names.', 'SELECT name FROM states LIMIT 12', 'easy', 'Table Exploration', 'Beginner', 'Select name from states.'),
('Show the first 8 rows from the cities table.', 'SELECT * FROM cities LIMIT 8', 'easy', 'Table Exploration', 'Beginner', ' * from cities.'),
('List city names and country names for the first 15 cities.', 'SELECT name, country_name FROM cities LIMIT 15', 'easy', 'Table Exploration', 'Beginner', 'cities already has country_name.'),
('List country names and ISO2 codes for the first 20 countries.', 'SELECT name, iso2 FROM countries LIMIT 20', 'easy', 'Table Exploration', 'Beginner', 'Select two columns.'),
('List country names and currencies for the first 20 countries.', 'SELECT name, currency FROM countries LIMIT 20', 'easy', 'Table Exploration', 'Beginner', ' currency column.'),
('List city names, state names, and country names for the first 15 cities.', 'SELECT name, state_name, country_name FROM cities LIMIT 15', 'easy', 'Table Exploration', 'Beginner', 'Select three columns from cities.'),
('List countries alphabetically by name.', 'SELECT name FROM countries ORDER BY name ASC LIMIT 25', 'medium', 'Sorting and Limiting', 'Beginner', 'ORDER BY name ASC keeps it alphabetic.'),
('List countries by population from highest to lowest.', 'SELECT name, population FROM countries ORDER BY population DESC LIMIT 10', 'medium', 'Sorting and Limiting', 'Beginner', 'Sort population descending and limit the result.'),
('List cities by population from highest to lowest.', 'SELECT name, country_name, population FROM cities ORDER BY population DESC LIMIT 10', 'medium', 'Sorting and Limiting', 'Beginner', ' BY population DESC.'),
('List states by population from highest to lowest.', 'SELECT name, country_name, population FROM states ORDER BY population DESC LIMIT 10', 'medium', 'Sorting and Limiting', 'Beginner', 'Sort states by population.'),
('Show the 10 countries with the highest GDP values.', 'SELECT name, gdp FROM countries ORDER BY gdp DESC LIMIT 10', 'medium', 'Sorting and Limiting', 'Beginner', ' gdp column.'),
('Show the 10 northernmost countries by latitude.', 'SELECT name, latitude FROM countries ORDER BY latitude DESC LIMIT 10', 'medium', 'Sorting and Limiting', 'Beginner', 'Higher latitude means farther north.'),
('Show the 10 southernmost countries by latitude.', 'SELECT name, latitude FROM countries ORDER BY latitude ASC LIMIT 10', 'medium', 'Sorting and Limiting', 'Beginner', 'Lower latitude means farther south.'),
('Show the 10 easternmost countries by longitude.', 'SELECT name, longitude FROM countries ORDER BY longitude DESC LIMIT 10', 'medium', 'Sorting and Limiting', 'Beginner', 'Sort longitude descending.'),
('Show the 10 westernmost countries by longitude.', 'SELECT name, longitude FROM countries ORDER BY longitude ASC LIMIT 10', 'medium', 'Sorting and Limiting', 'Beginner', 'Sort longitude ascending.'),
('List the first 20 unique regions from countries.', 'SELECT DISTINCT region FROM countries LIMIT 20', 'medium', 'Table Exploration', 'Beginner', ' on region.'),
('List the first 20 unique subregions from countries.', 'SELECT DISTINCT subregion FROM countries LIMIT 20', 'medium', 'Table Exploration', 'Beginner', ' on subregion.'),
('List the first 20 unique country codes in cities.', 'SELECT DISTINCT country_code FROM cities LIMIT 20', 'medium', 'Table Exploration', 'Beginner', ' country_code.'),
('List the first 20 unique state types.', 'SELECT DISTINCT type FROM states LIMIT 20', 'medium', 'Table Exploration', 'Beginner', ' type from states.'),
('List country names and nationalities alphabetically by nationality.', 'SELECT name, nationality FROM countries ORDER BY nationality ASC LIMIT 20', 'medium', 'Sorting and Limiting', 'Beginner', 'Select name and nationality, then sort.'),
('List city names and coordinates for the first 10 cities.', 'SELECT name, latitude, longitude FROM cities LIMIT 10', 'medium', 'Table Exploration', 'Beginner', 'Coordinates  and longitude.'),
('List country names, regions, and subregions for the first 25 countries.', 'SELECT name, region, subregion FROM countries LIMIT 25', 'medium', 'Table Exploration', 'Beginner', 'Select geography classification columns.'),
('Show country names with phone codes for the first 20 countries.', 'SELECT name, phonecode FROM countries LIMIT 20', 'hard', 'Table Exploration', 'Beginner', ' phonecode column.'),
('Show city names with state codes for the first 20 cities.', 'SELECT name, state_code FROM cities LIMIT 20', 'hard', 'Table Exploration', 'Beginner', 'Select state_code from cities.'),
('List countries ordered by currency code, then country name.', 'SELECT name, currency FROM countries ORDER BY currency ASC, name ASC LIMIT 25', 'hard', 'Sorting and Limiting', 'Beginner', 'ORDER BY can  than one column.'),
('List cities ordered by country name, then city name.', 'SELECT country_name, name FROM cities ORDER BY country_name ASC, name ASC LIMIT 25', 'hard', 'Sorting and Limiting', 'Beginner', 'Sort by country_name first.'),
('Find the country named Japan.', 'SELECT * FROM countries WHERE name = ''Japan''', 'easy', 'Filtering', 'Intermediate', ' name = ''Japan''.'),
('Find the country named Belgium.', 'SELECT name, capital, population FROM countries WHERE name = ''Belgium''', 'easy', 'Filtering', 'Intermediate', 'Filter countries by name.'),
('Find all countries in the Asia region.', 'SELECT name FROM countries WHERE region = ''Asia''', 'easy', 'Filtering', 'Intermediate', ' region = ''Asia''.'),
('Find all countries in the Europe region.', 'SELECT name FROM countries WHERE region = ''Europe''', 'easy', 'Filtering', 'Intermediate', 'Filter by region.'),
('Find all countries in the Western Europe subregion.', 'SELECT name FROM countries WHERE subregion = ''Western Europe''', 'easy', 'Filtering', 'Intermediate', '.'),
('Find cities in Belgium using country_code.', 'SELECT name FROM cities WHERE country_code = ''BE''', 'easy', 'Filtering', 'Intermediate', 'Belgium uses BE.'),
('Find states in Canada using country_code.', 'SELECT name FROM states WHERE country_code = ''CA''', 'easy', 'Filtering', 'Intermediate', 'Filter states by country_code.'),
('Find countries with population greater than 100 million.', 'SELECT name, population FROM countries WHERE population > 100000000', 'medium', 'Filtering', 'Intermediate', 'Use > with population.'),
('Find countries with population less than 100 thousand.', 'SELECT name, population FROM countries WHERE population < 100000', 'medium', 'Filtering', 'Intermediate', 'Use < with population.'),
('Find cities with population greater than 10 million.', 'SELECT name, country_name, population FROM cities WHERE population > 10000000', 'medium', 'Filtering', 'Intermediate', 'Filter cities by population.'),
('Find cities with population between 1 million and 5 million.', 'SELECT name, country_name, population FROM cities WHERE population BETWEEN 1000000 AND 5000000', 'medium', 'Filtering', 'Intermediate', ' low AND high.'),
('Find countries whose names start with Z.', 'SELECT name FROM countries WHERE name LIKE ''Z%''', 'medium', 'Filtering', 'Intermediate', 'LIKE ''Z%'' means starts with Z.'),
('Find cities whose names end with burg.', 'SELECT name, country_name FROM cities WHERE name LIKE ''%burg''', 'medium', 'Filtering', 'Intermediate', 'LIKE ''%burg'' means ends with burg.'),
('Find countries that  Euro.', 'SELECT name FROM countries WHERE currency_name = ''Euro''', 'medium', 'Filtering', 'Intermediate', '.'),
('Find countries that  currency code.', 'SELECT name FROM countries WHERE currency = ''USD''', 'medium', 'Filtering', 'Intermediate', 'Filter by currency code.'),
('Find countries in either Oceania or Polar regions.', 'SELECT name, region FROM countries WHERE region IN (''Oceania'', ''Polar'')', 'medium', 'Filtering', 'Intermediate', ' with two region names.'),
('Find countries with unknown GDP.', 'SELECT name FROM countries WHERE gdp IS NULL', 'medium', 'Filtering', 'Intermediate', ' NULL.'),
('Find countries with known GDP.', 'SELECT name, gdp FROM countries WHERE gdp IS NOT NULL', 'medium', 'Filtering', 'Intermediate', ' NOT NULL.'),
('Find countries in Europe with population above 50 million.', 'SELECT name, population FROM countries WHERE region = ''Europe'' AND population > 50000000', 'hard', 'Filtering', 'Intermediate', 'Combine conditions with AND.'),
('Find countries in Asia or Africa with GDP above 500000.', 'SELECT name, region, gdp FROM countries WHERE region IN (''Asia'', ''Africa'') AND gdp > 500000', 'hard', 'Filtering', 'Intermediate', 'Combine IN with a GDP comparison.'),
('Show country names in uppercase.', 'SELECT UPPER(name) FROM countries LIMIT 25', 'hard', 'Scalar Functions', 'Intermediate', '(name).'),
('Show country names in lowercase.', 'SELECT LOWER(name) FROM countries LIMIT 25', 'hard', 'Scalar Functions', 'Intermediate', '(name).'),
('Show each country name and the length of its name.', 'SELECT name, LENGTH(name) FROM countries LIMIT 25', 'hard', 'Scalar Functions', 'Intermediate', '(name).'),
('Round country latitude values to one decimal place.', 'SELECT name, ROUND(latitude, 1) FROM countries LIMIT 25', 'hard', 'Scalar Functions', 'Intermediate', 'ROUND(latitude, 1).'),
('Count all countries.', 'SELECT COUNT(*) FROM countries', 'easy', 'Aggregate Functions', 'Intermediate', 'COUNT(*) counts rows.'),
('Count all states.', 'SELECT COUNT(*) FROM states', 'easy', 'Aggregate Functions', 'Intermediate', '(*) on states.'),
('Count all cities.', 'SELECT COUNT(*) FROM cities', 'easy', 'Aggregate Functions', 'Intermediate', '(*) on cities.'),
('Count countries with a known capital.', 'SELECT COUNT(capital) FROM countries', 'medium', 'Aggregate Functions', 'Intermediate', 'COUNT(column) skips NULL values.'),
('Find the total population of all countries.', 'SELECT SUM(population) FROM countries', 'medium', 'Aggregate Functions', 'Intermediate', '(population).'),
('Find the average country population.', 'SELECT AVG(population) FROM countries', 'medium', 'Aggregate Functions', 'Intermediate', '(population).'),
('Find the largest country population.', 'SELECT MAX(population) FROM countries', 'medium', 'Aggregate Functions', 'Intermediate', '(population).'),
('Find the smallest known country population.', 'SELECT MIN(population) FROM countries WHERE population IS NOT NULL', 'medium', 'Aggregate Functions', 'Intermediate', 'Filter out NULL before MIN.'),
('Find the average GDP of countries with known GDP.', 'SELECT AVG(gdp) FROM countries WHERE gdp IS NOT NULL', 'hard', 'Aggregate Functions', 'Intermediate', ' with IS NOT NULL.'),
('Count how many distinct currencies exist.', 'SELECT COUNT(DISTINCT currency) FROM countries', 'hard', 'Aggregate Functions', 'Intermediate', '(DISTINCT currency).'),
('Find the total population of cities in Japan.', 'SELECT SUM(population) FROM cities WHERE country_name = ''Japan''', 'hard', 'Aggregate Functions', 'Intermediate', 'cities has country_name.'),
('Find the average city population in Belgium.', 'SELECT AVG(population) FROM cities WHERE country_code = ''BE''', 'hard', 'Aggregate Functions', 'Intermediate', 'Filter by BE before AVG.'),
('Find the most populated city in India by sorting.', 'SELECT name, population FROM cities WHERE country_name = ''India'' ORDER BY population DESC LIMIT 1', 'hard', 'Sorting and Limiting', 'Intermediate', 'Filter India, sort descending, limit 1.'),
('Find the highest GDP country by sorting.', 'SELECT name, gdp FROM countries WHERE gdp IS NOT NULL ORDER BY gdp DESC LIMIT 1', 'hard', 'Sorting and Limiting', 'Intermediate', 'Sort known GDP values descending.'),
('Find the lowest populated country with known population.', 'SELECT name, population FROM countries WHERE population IS NOT NULL ORDER BY population ASC LIMIT 1', 'hard', 'Sorting and Limiting', 'Intermediate', 'Filter NULL population, sort ascending.'),
('List countries in the Americas that  United States dollar.', 'SELECT name FROM countries WHERE region = ''Americas'' AND currency = ''USD''', 'hard', 'Filtering', 'Intermediate', ' and currency together.'),
('List each city with its country by joining cities to countries.', 'SELECT cities.name, countries.name FROM cities INNER JOIN countries ON cities.country_id = countries.id LIMIT 25', 'easy', 'Joins', 'Advanced', 'Join on country_id = id.'),
('List each city with its state by joining cities to states.', 'SELECT cities.name, states.name FROM cities INNER JOIN states ON cities.state_id = states.id LIMIT 25', 'easy', 'Joins', 'Advanced', 'Join cities.state_id to states.id.'),
('List each state with its country by joining states to countries.', 'SELECT states.name, countries.name FROM states INNER JOIN countries ON states.country_id = countries.id LIMIT 25', 'easy', 'Joins', 'Advanced', 'Join states.country_id to countries.id.'),
('List cities in France using a join to countries.', 'SELECT cities.name FROM cities INNER JOIN countries ON cities.country_id = countries.id WHERE countries.name = ''France''', 'medium', 'Joins', 'Advanced', 'Join, then filter countries.name.'),
('List states in the United States using a join to countries.', 'SELECT states.name FROM states INNER JOIN countries ON states.country_id = countries.id WHERE countries.name = ''United States''', 'medium', 'Joins', 'Advanced', 'Join states to countries and filter.'),
('List cities, states, and countries using two joins.', 'SELECT cities.name, states.name, countries.name FROM cities INNER JOIN states ON cities.state_id = states.id INNER JOIN countries ON cities.country_id = countries.id LIMIT 25', 'medium', 'Joins', 'Advanced', ' INNER JOIN clauses.'),
('List cities in countries that  Euro.', 'SELECT cities.name, countries.name FROM cities INNER JOIN countries ON cities.country_id = countries.id WHERE countries.currency_name = ''Euro'' LIMIT 50', 'medium', 'Joins', 'Advanced', 'Join cities to countries and filter currency_name.'),
('List cities in Western Europe using a join.', 'SELECT cities.name, countries.name FROM cities INNER JOIN countries ON cities.country_id = countries.id WHERE countries.subregion = ''Western Europe'' LIMIT 50', 'medium', 'Joins', 'Advanced', 'Filter countries.subregion after the join.'),
('Count countries in each region.', 'SELECT region, COUNT(*) FROM countries GROUP BY region', 'easy', 'Group By', 'Advanced', 'GROUP BY region.'),
('Count countries in each subregion.', 'SELECT subregion, COUNT(*) FROM countries GROUP BY subregion', 'easy', 'Group By', 'Advanced', 'GROUP BY subregion.'),
('Find total country population for each region.', 'SELECT region, SUM(population) FROM countries GROUP BY region', 'medium', 'Group By', 'Advanced', 'SUM population per region.'),
('Find average GDP for each region.', 'SELECT region, AVG(gdp) FROM countries WHERE gdp IS NOT NULL GROUP BY region', 'medium', 'Group By', 'Advanced', 'Filter known GDP before grouping.'),
('Count cities in each country and show country name.', 'SELECT countries.name, COUNT(cities.id) FROM countries INNER JOIN cities ON countries.id = cities.country_id GROUP BY countries.name', 'hard', 'Group By', 'Advanced', 'Join, then GROUP BY country name.'),
('Find countries with more than 100 cities listed.', 'SELECT countries.name, COUNT(cities.id) FROM countries INNER JOIN cities ON countries.id = cities.country_id GROUP BY countries.name HAVING COUNT(cities.id) > 100', 'hard', 'Group By', 'Advanced', ' after GROUP BY.'),
('Find states whose total city population is above 5 million.', 'SELECT states.name, SUM(cities.population) FROM states INNER JOIN cities ON states.id = cities.state_id GROUP BY states.name HAVING SUM(cities.population) > 5000000', 'hard', 'Group By', 'Advanced', 'Join states and cities, then HAVING SUM.'),
('Find the city with the largest population using a subquery.', 'SELECT name FROM cities WHERE population = (SELECT MAX(population) FROM cities)', 'medium', 'Subqueries', 'Advanced', '(population) inside a subquery.'),
('Find the country with the highest GDP using a subquery.', 'SELECT name FROM countries WHERE gdp = (SELECT MAX(gdp) FROM countries)', 'medium', 'Subqueries', 'Advanced', 'Compare gdp to SELECT MAX(gdp).'),
('Find cities in the same country as Tokyo.', 'SELECT name FROM cities WHERE country_id = (SELECT country_id FROM cities WHERE name = ''Tokyo'' AND country_name = ''Japan'' LIMIT 1)', 'medium', 'Subqueries', 'Advanced', 'The subquery finds Tokyo''s country_id.'),
('Find states in the same country as California.', 'SELECT name FROM states WHERE country_id = (SELECT country_id FROM states WHERE name = ''California'' AND country_name = ''United States'' LIMIT 1)', 'medium', 'Subqueries', 'Advanced', 'Find California''s country_id first.'),
('Find countries that have at least one city above 10 million population.', 'SELECT name FROM countries WHERE id IN (SELECT country_id FROM cities WHERE population > 10000000)', 'hard', 'Subqueries', 'Advanced', ' with a cities subquery.'),
('Find cities whose population is above the average city population.', 'SELECT name FROM cities WHERE population > (SELECT AVG(population) FROM cities)', 'hard', 'Subqueries', 'Advanced', 'Compare population to AVG(population).'),
('Find countries whose GDP is below the average known GDP.', 'SELECT name FROM countries WHERE gdp < (SELECT AVG(gdp) FROM countries WHERE gdp IS NOT NULL)', 'hard', 'Subqueries', 'Advanced', 'The subquery calculates average known GDP.'),
('Find countries that have at least one state above 20 million population.', 'SELECT name FROM countries WHERE id IN (SELECT country_id FROM states WHERE population > 20000000)', 'hard', 'Subqueries', 'Advanced', ' with states.'),
('List countries that have at least one city.', 'SELECT name FROM countries c WHERE EXISTS (SELECT 1 FROM cities ci WHERE ci.country_id = c.id)', 'medium', 'Correlated Subqueries', 'Advanced', ' with the outer country id.'),
('Find countries whose population is above the average for their region.', 'SELECT name FROM countries c1 WHERE population > (SELECT AVG(population) FROM countries c2 WHERE c2.region = c1.region)', 'hard', 'Correlated Subqueries', 'Advanced', 'The subquery must match the outer row region.'),
('Find cities whose population is above the average city population in their country.', 'SELECT name FROM cities c1 WHERE population > (SELECT AVG(population) FROM cities c2 WHERE c2.country_id = c1.country_id)', 'hard', 'Correlated Subqueries', 'Advanced', 'Correlate by country_id.'),
('List each country with its largest city population.', 'SELECT c.name, (SELECT MAX(ci.population) FROM cities ci WHERE ci.country_id = c.id) FROM countries c', 'hard', 'Correlated Subqueries', 'Advanced', ' subquery in the SELECT list.'),
('List each state with its total city population.', 'SELECT s.name, (SELECT SUM(ci.population) FROM cities ci WHERE ci.state_id = s.id) FROM states s', 'hard', 'Correlated Subqueries', 'Advanced', 'Subquery sums cities for each state.'),
('Find the largest city in each country.', 'SELECT ci.name FROM cities ci WHERE ci.population = (SELECT MAX(ci2.population) FROM cities ci2 WHERE ci2.country_id = ci.country_id)', 'hard', 'Correlated Subqueries', 'Advanced', 'Compare each city to max population in its country.'),
('Find countries whose GDP is greater than the average GDP of their subregion.', 'SELECT name FROM countries c1 WHERE gdp > (SELECT AVG(gdp) FROM countries c2 WHERE c2.subregion = c1.subregion AND c2.gdp IS NOT NULL)', 'hard', 'Correlated Subqueries', 'Advanced', 'Correlate by subregion and ignore NULL GDP.');
